trainer:
  validation_before_training: true
  validation_every_it: -1
  ckpt_dir: /tmp/exp_cifar10
  init_ckpt: ''
  resume_from_ckpt: true
  ckpt_every_it: -1
  ckpt_to_keep: 3
  display_loss_every_it: 5
  verbose: true
trainer_class: SingleGPUTrainer
timekeeping:
  nb_epochs: 3
  batch_size: 32
  nb_samples_per_epoch: 640
timekeeping_class: Timekeeping
problem:
  model:
    model_name: resnet18
    pretrained: ''
    input_size: !!python/tuple
    - 64
    - 64
    nb_channels: 3
    nb_classes: 10
    drop_rate: 0.0
  model_class: ModelFactory
  optimizer:
    lr_schedule: 
      lr: 0.001
      lr_decay_rate: 0.8
      lr_decay_frequency: 1
    lr_schedule_class: LRExponentialDecayFactory
    optimizer: sgd
    betas: !!python/tuple
    - 0.9
    - 0.999
    clipnorm: -1.0
    clipvalue: -1.0
    lr_warmup: -1
  optimizer_class: OptimizerFactory
  binary_loss: false
  weight_decay: 0.01
  mixed_precision: false
  save_input_dtype: float32
problem_class: ClassificationProblem
train_dataset:
  dataset_name: cifar10
  split: train
  input_size: !!python/tuple
  - 64
  - 64
  batch_size: 32
  repeat: true
  shuffle: true
  nb_samples: -1
  cache: false
  dtype: float32
train_dataset_class: TFDSWrapper
val_dataset:
  dataset_name: cifar10
  split: test
  input_size: !!python/tuple
  - 64
  - 64
  batch_size: 32
  repeat: false
  shuffle: false
  nb_samples: 320
  cache: false
  dtype: float32
val_dataset_class: TFDSWrapper
logging_level: 30
log_wandb: false
experiment_name: default
project_name: default
entity: default
cfg_file: ''
