name: Publish package

on: workflow_dispatch
#  release:
#    types:
#      - created

jobs:
  publish:
    name: Publish python package to PyPi
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: [ '3.7' ]
        poetry: [ '1.1.6' ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry }}

    - name: Set Poetry config
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Install Dependencies
      run: poetry install -E timm

    - name: Publish package
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config repositories.test-pypi https://test.pypi.org/legacy/
        poetry config pypi-token.test-pypi $TEST_PYPI_TOKEN
        poetry build
        poetry publish -r test-pypi
